"""Add idempotency_key to orders

Revision ID: 7960934d5e4c
Revises: cc59e73a4462
Create Date: 2026-10-09 07:46:36.134343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7960934d5e4c"
down_revision: Union[str, None] = "cc59e73a4462"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("idempotency_key", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_orders_idempotency_key"), "orders", ["idempotency_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_idempotency_key"), table_name="orders")
    op.drop_column("orders", "idempotency_key")
    # ### end Alembic commands ###
